name: curl_logger_dio_interceptor_example
description: Demonstrates how to use the curl_logger_dio_interceptor plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.7.0

  flutter:
    sdk: flutter

  curl_logger_dio_interceptor:
    # When depending on this package from a real application you should use:
    #   curl_logger_dio_interceptor: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true